steps:
  - name: "bats/bats"
    id: "Run bats tests to validate tester script"
    entrypoint: "bash"
    dir: "scripts"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        bats bats-tests/*

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Create artifact registry repository"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        if `gcloud artifacts repositories list | grep -q "cloud-build-helper-docker"`;
        then
          echo "Repository already exists."
        else
          gcloud artifacts repositories create cloud-build-helper-docker --repository-format=docker --location=us-central1
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: "Build docker image"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        docker build -f Dockerfile -t us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-build-helper-docker/cloud-build-helper-docker:0.1 .

  - name: "gcr.io/cloud-builders/docker"
    id: "Push docker image"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-build-helper-docker/cloud-build-helper-docker:0.1
options:
  substitutionOption: "ALLOW_LOOSE"
